services:
  tailscale-derp:
    image: 'yangchuansheng/ip_derper'
    restart: always
    environment:
      - 'TZ=${TZ:-Asia/Shanghai}'
      - 'DERP_ADDR=:12345'
    ports:
      - '12345:12345'
      - '3478:3478/udp'
    cpuset: ${CPUSET}