services:
  tailscale-derp:
    image: 'yangchuansheng/ip_derper'
    restart: always
    environment:
      - 'TZ=${TZ:-Asia/Shanghai}'
    ports:
      - '12345:443'
      - '3478:3478/udp'
    cpuset: ${CPUSET}