services:
  open-webui:
    image: 'ghcr.io/open-webui/open-webui:${OPEN_WEBUI_IMAGE_VERSION:-ollama}'
    restart: unless-stopped
    environment:
      - 'TZ=${TZ:-Asia/Shanghai}'
      - 'PUID=${PUID:-1000}'
      - 'PGID=${PGID:-100}'
    ports:
      - '3002:8080'
    volumes:
      - ${OPEN_WEBUI_VOLUME:-.}/data:/app/backend/data
      - ${OPEN_WEBUI_VOLUME:-.}/ollama:/root/.ollama
    cpuset: ${CPUSET}
