services:
  iperf3:
    image: 'networkstatic/iperf3:${IPERF3_IMAGE_VERSION:-latest}'
    restart: always
    pid: host
    command: -s
    environment:
      - 'TZ=${TZ:-Asia/Shanghai}'
    cpuset: ${CPUSET}